name: Deploy to S3

on:
  push:
    branches:
      - devel
      - stage
      - prod

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar los artefactos generados por el workflow de CI
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # 2. Configurar AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Subir los artefactos al bucket S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://fullstack-labs-devops-${{ github.ref }}/ --delete
